#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

namespace DBD.SaveGame.Editor
{
    public static class SaveGameGeneratorCode
    {
        [MenuItem("Tools/Save Game/Generate Properties")]
        public static void Generate()
        {
            string[] guids = AssetDatabase.FindAssets("t:Script");

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                string code = File.ReadAllText(path);

                if (!code.Contains("partial class")) continue;
                if (!code.Contains("[SerializeField]")) continue;
                if (!code.Contains("SaveValue<") && !code.Contains("SaveList<")) continue;

                GenerateForFile(path, code);
            }

            AssetDatabase.Refresh();
            Debug.Log("SaveGame generation code done");
        }

        private static void GenerateForFile(string path, string code)
        {
            var classMatch = Regex.Match(code, @"partial class (\w+)");
            if (!classMatch.Success) return;

            string className = classMatch.Groups[1].Value;


            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("using DBD.SaveGame;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"public partial class {className}");
            sb.AppendLine("{");

            var fieldRegex = new Regex(
                @"\[SerializeField\]\s+private\s+SaveValue<(\w+)>\s+(\w+)",
                RegexOptions.Multiline
            );

            foreach (Match match in fieldRegex.Matches(code))
            {
                string type = match.Groups[1].Value;
                string field = match.Groups[2].Value;
                string prop = UpperFirst(field);

                sb.AppendLine(
                    $"\tpublic {type} {prop}\n\t{{\n\t\tget => {field}.Value;\n\t\tset => {field}.Value = value;\n\t}}\n");
            }

            // ---------- SaveList ----------
            var saveListRegex = new Regex(
                @"\[SerializeField\]\s+private\s+SaveList<([^>]+)>\s+(\w+)",
                RegexOptions.Multiline
            );
            foreach (Match match in saveListRegex.Matches(code))
            {
                string type = match.Groups[1].Value;
                string field = match.Groups[2].Value;
                string prop = UpperFirst(field);

                sb.AppendLine(
                    $"\tpublic SaveList<{type}> {prop}\n\t{{\n\t\tget => {field};\n\t\tset\n\t\t{{\n\t\t\t{field} = value;\n\t\t}}\n\t}}\n");
            }

            sb.AppendLine("}");


            string generatedPath = path.Replace(".cs", ".Public.cs");
            File.WriteAllText(generatedPath, sb.ToString());
        }

        private static string UpperFirst(string name)
        {
            return char.ToUpper(name[0]) + name.Substring(1);
        }
    }
}
#endif